---
- hosts: sensuclients
  become: true
  become_user: root
  become_method: sudo
  roles:
     - sensu
  vars:
    sensu_install_server: false
    sensu_insntall_uchiwa: false
    sensu_install_client: true
    sensu_cert_file_name: "sensu_client_cert.pem"
    sensu_key_file_name: "sensu_client_key.pem"
    sensu_client_hostname: "ansibleprovisionedhost"  ## TODO: get the hostname dynamically
    sensu_server_rabbitmq_hostname:  "ec2-54-73-140-19.eu-west-1.compute.amazonaws.com"
    sensu_server_rabbitmq_port: 35671
    sensu_server_rabbitmq_user: "sensu"
    sensu_server_rabbitmq_password: "sensu"
    
  tasks:
  - name: copy all the checks 
    copy:
      src=files/sensu/checks/
      dest=/etc/sensu/conf.d/
      owner="{{ sensu_user }}"
      group="{{ sensu_group }}"
      mode=0640
    notify:
      - restart sensu client

  - name: install the gems for the plugins
    command: "/opt/sensu/embedded/bin/gem install {{ item.gem }} --no-doc"
    with_items: 
      - { gem: "sensu-plugins-cpu-checks" }
      - { gem: "sensu-plugins-disk-checks" }
      - { gem: "sensu-plugins-memory-checks" }
      - { gem: "sensu-plugins-process-checks" }
